### ISSUE TITLE
how to make it work in {{ 2019 > python 3.5 or higher > Django 2 }}

### ISSUE THREAD

**Issue by Ali-Kamel** [dokterbob/django-wishlist#4]
thanks dokterbob and all who worked in this small cool project

first thing first you need to upgrade every file on the source code of the wish-list and that's what we gonna do 

1- urls
1.1- patterns is not used anymore in django 2 so we get rid of it 

urlpatterns = (url(r'^$',WishlistView.as_view(), name='wishlist'), etc etc 
#-------------------------------------------------------------------------------

2- view
2.1- user.is_authenticated() is not a function anymore ' method ' in django 2 so we will only remove the () to be user.is_authenticated

2.2- unicode is not used anymore in python 3 and it's replaced by str so replace the 3 of the unicode in the views to str

2.3 - change from django.core.urlresolvers import reverse
to from django.urls import reverse
#-------------------------------------------------------------------------------
3- models 
3.1- user need a third parameter and it's on_delete so add  on_delete=models.CASCADE to it

3.2- item need a third parameter and it's on_delete so add  on_delete=models.CASCADE to it

3.3 - comment out part.
{     def __unicode__(self):
        """ Wrap unicode of item. """

        assert self.item

        return unicode(self.item)

    def get_absolute_url(self):
        """ Return absolute URL for item. """

        return self.item.get_absolute_url() }
#-------------------------------------------------------------------------------
4 - context_processors.py
4.1 - user.is_authenticated() is not a function anymore ' method ' in django 2 so we will only remove the () to be user.is_authenticated
#-------------------------------------------------------------------------------
any way that's how it worked with me through fixing all the errors that came out to me, if you have any comment or something wrong i did please comment here thanks !

**Comment by Ali-Kamel** [comment]
also in wishlist_tags.py i commented these 3 lines
    # assert 'user' in context
    # assert hasattr(item, 'pk')
    # assert hasattr(item, 'wishlistitem_set')
because i had an assertions error i hope we can find another fix but this fixed it for now
thanks again

**Comment by treezjoz** [comment]
thank you..this really helped me
